//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestoreMy2FA.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RestoreMy2FA.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive file cannot be processed.
        /// </summary>
        internal static string ArchiveFileCannotBeProcessed {
            get {
                return ResourceManager.GetString("ArchiveFileCannotBeProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Database file (&apos;databases&apos; file).
        /// </summary>
        internal static string DatabaseFile {
            get {
                return ResourceManager.GetString("DatabaseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Db File cannot be recognized.
        /// </summary>
        internal static string DbFileUnrecognized {
            get {
                return ResourceManager.GetString("DbFileUnrecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you copy file to the program directory? (y/n).
        /// </summary>
        internal static string DidYouCopyFileToTheProgramDirectory {
            get {
                return ResourceManager.GetString("DidYouCopyFileToTheProgramDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist. Specified path: {0}.
        /// </summary>
        internal static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments: [archive | db  path_to_file].
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} keys exported.
        /// </summary>
        internal static string NKeysExported {
            get {
                return ResourceManager.GetString("NKeysExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input file path:.
        /// </summary>
        internal static string PleaseInputFilePath {
            get {
                return ResourceManager.GetString("PleaseInputFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to continue....
        /// </summary>
        internal static string PressAnyKey {
            get {
                return ResourceManager.GetString("PressAnyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Titanium Backup Archive (com.google.android.apps.authenticator2.tar.gz).
        /// </summary>
        internal static string TitaniumBackupArchive {
            get {
                return ResourceManager.GetString("TitaniumBackupArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Argument {0}. Expected: archive or db.
        /// </summary>
        internal static string UnexpectedArgument {
            get {
                return ResourceManager.GetString("UnexpectedArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected behaviour.
        /// </summary>
        internal static string UnexpectedBehaviour {
            get {
                return ResourceManager.GetString("UnexpectedBehaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do You have? (press 1 or 2).
        /// </summary>
        internal static string WhatDoYouHave {
            get {
                return ResourceManager.GetString("WhatDoYouHave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong count of arguments. Two or empty expected..
        /// </summary>
        internal static string WrongCountOfArguments {
            get {
                return ResourceManager.GetString("WrongCountOfArguments", resourceCulture);
            }
        }
    }
}
